/**
 * Rebuilds the category tree from the pre-parsed nom_tree.json
 * (generated by: python3 scripts/parse-nom-tree.py)
 *
 *  1. Wipes existing categories
 *  2. Inserts top + sub categories from the nomenclature tree
 *  3. Matches each StockItem by name → sets StockItem.categoryId
 */
import * as fs from 'fs';
import * as path from 'path';
import { db } from '../lib/db';

const JSON_PATH = path.join(__dirname, '../nom_tree.json');

type NomProduct = { name: string; topCategory: string; subCategory: string };
type TreeData = {
  topCategories: string[];
  subMap: Record<string, string[]>;
  products: NomProduct[];
};

function slugify(s: string): string {
  const translit: Record<string, string> = {
    а:'a',б:'b',в:'v',г:'g',д:'d',е:'e',ё:'e',ж:'zh',з:'z',и:'i',й:'j',
    к:'k',л:'l',м:'m',н:'n',о:'o',п:'p',р:'r',с:'s',т:'t',у:'u',ф:'f',
    х:'kh',ц:'ts',ч:'ch',ш:'sh',щ:'sch',ъ:'',ы:'y',ь:'',э:'e',ю:'yu',я:'ya',
  };
  return s.toLowerCase()
    .split('').map(c => translit[c] ?? c).join('')
    .replace(/\s+/g,'-').replace(/[^a-z0-9-]/g,'').replace(/-+/g,'-')
    .replace(/^-|-$/g,'').slice(0,80);
}

function normalize(s: string): string {
  return s.toLowerCase().replace(/\s+/g,' ').trim();
}

async function main() {
  if (!fs.existsSync(JSON_PATH)) {
    console.error('nom_tree.json not found — run: python3 scripts/parse-nom-tree.py');
    process.exit(1);
  }
  const tree: TreeData = JSON.parse(fs.readFileSync(JSON_PATH, 'utf-8'));
  const { topCategories, subMap, products } = tree;

  console.log(`Tree: ${topCategories.length} top, ${Object.values(subMap).flat().length} sub, ${products.length} products`);

  // Build lookup
  const nameToCategory = new Map<string, { topCategory: string; subCategory: string }>();
  for (const p of products) {
    nameToCategory.set(normalize(p.name), { topCategory: p.topCategory, subCategory: p.subCategory });
  }

  // All category-node names (these rows in StockItem are ghost/orphan rows)
  const allCategoryNames = new Set([
    ...topCategories.map(normalize),
    ...Object.values(subMap).flat().map(normalize),
  ]);

  // ── 1. Clear old category refs ──
  console.log('Clearing old category refs…');
  await db.stockItem.updateMany({ data: { categoryId: null } });
  await db.product.updateMany({ data: { categoryId: null } });
  await db.category.deleteMany({});

  // ── 2. Insert new categories ──
  console.log('Inserting new categories…');
  const topCatIds: Record<string, number> = {};
  const subCatIds: Record<string, Record<string, number>> = {};

  for (const topName of topCategories) {
    const row = await db.category.create({ data: { name: topName, slug: slugify(topName), level: 1 } });
    topCatIds[topName] = row.id;
    subCatIds[topName] = {};
    for (const subName of subMap[topName] ?? []) {
      const sub = await db.category.create({ data: { name: subName, slug: slugify(subName), level: 2, parentId: row.id } });
      subCatIds[topName][subName] = sub.id;
    }
  }
  console.log(`  Inserted categories.`);

  // ── 3. Assign categories to StockItems ──
  console.log('Matching stock items…');
  const allStock = await db.stockItem.findMany({ select: { id: true, name: true } });

  let matched = 0;
  let ghost = 0;

  const updates: Array<{ id: number; categoryId: number }> = [];

  for (const item of allStock) {
    const norm = normalize(item.name);
    const catInfo = nameToCategory.get(norm);
    if (catInfo) {
      const { topCategory, subCategory } = catInfo;
      const catId = (subCategory && subCatIds[topCategory]?.[subCategory])
        ? subCatIds[topCategory][subCategory]
        : topCatIds[topCategory];
      if (catId) {
        updates.push({ id: item.id, categoryId: catId });
        matched++;
        continue;
      }
    }
    if (allCategoryNames.has(norm)) ghost++;
  }

  // Batch updates in chunks of 500
  const CHUNK = 500;
  for (let i = 0; i < updates.length; i += CHUNK) {
    const chunk = updates.slice(i, i + CHUNK);
    await Promise.all(chunk.map(u => db.stockItem.update({ where: { id: u.id }, data: { categoryId: u.categoryId } })));
    process.stdout.write(`\r  ${Math.min(i + CHUNK, updates.length)}/${updates.length}`);
  }
  console.log();

  const unmatched = allStock.length - matched - ghost;
  console.log(`\nResults:`);
  console.log(`  Matched (got categoryId): ${matched}`);
  console.log(`  Ghost category-name rows:  ${ghost}`);
  console.log(`  Unmatched (no catId):      ${unmatched}`);

  await db.$disconnect();
}

main().catch(e => { console.error(e); process.exit(1); });
